baseURL = 'https://superelgato.netlify.app/'
theme = "sc"
defaultContentLanguage = "fr"
title = 'Super Chat'
publishDir = "public"

[menu]
  [[menu.main]]
    name = "txt"
    pre = "txt"
    url = "/txt/"
    title = "Se rendre sur la page txt"
    weight = 1
	[[menu.main]]
    name = "shop"
    pre = "shop"
    url = "/shop/"
    title = "Se rendre sur la page Projets"
    weight = 3
  [[menu.main]]
    name = "info"
    pre = "info"
		pageRef= "/info"
    url = "/info/"
    title = "Se rendre sur la page info"
    weight = 5
sectionPagesMenu = "main"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
# Plugins
[params.plugins]
  # JS Plugins
  [[params.plugins.js]]
  URL = "https://code.jquery.com/jquery-3.7.1.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js"
  [[params.plugins.js]]
  URL = "https://unpkg.com/imagesloaded@5/imagesloaded.pkgd.min.js"
  [[params.plugins.js]]
  URL = "/js/slick.min.js"
  [[params.plugins.js]]
  URL = "/js/script.js"
  [[params.plugins.js]]
  URL = "/js/cookie.js"
