baseURL = "https://superchat.amoskhachut.fr/"
theme = "sc"
defaultContentLanguage = "fr"
title = 'Super Chat'

[menu]
  [[menu.main]]
    name = "maison"
    pre = "maison"
    url = "/"
    title = "Se rendre sur la page d’accueil"
    weight = 1
  [[menu.main]]
    name = "txt."
    pre = "txt"
    url = "/txt/txt-1/"
    title = "Se rendre sur la page txt"
    weight = 2
  [[menu.main]]
    name = "info"
    pre = "info"
		pageRef= "/info"
    url = "/info/"
    title = "Se rendre sur la page info"
    weight = 3
sectionPagesMenu = "main"

cleanDestinationDir = true
[markup.goldmark.renderer]
	unsafe = true
