baseURL = "https://superchat.amoskhachut.fr/"
theme = "sc"
defaultContentLanguage = "fr"
publishDir = "public"

[menu]
  [[menu.main]]
    name = "txt"
    pre = "txt"
    url = "/txt/txt-1/"
    title = "Se rendre sur la page txt"
    weight = 1
	[[menu.main]]
    name = "shop"
    pre = "shop"
    url = "/shop/"
    title = "Se rendre sur la page Projets"
    weight = 3
  [[menu.main]]
    name = "info"
    pre = "info"
		pageRef= "/info"
    url = "/info/"
    title = "Se rendre sur la page info"
    weight = 5
sectionPagesMenu = "main"
