[build]
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.121.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"


[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/favicon/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/css/minified/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"