[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.121.2"   # set to the version you use locally
  HUGO_ENABLEGITINFO = "true"  # optional, if you rely on .GitInfo

[dev]
  command = "hugo server -p 1314 --bind 127.0.0.1"
  targetPort = 1314
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"

[context.production.environment]
  HUGO_VERSION = "0.121.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"


[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/favicon/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/css/minified/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"