backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
  branch: main # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow

# collections
collections:
  - name: 'img'
    label: 'img'
    folder: 'themes/sc/content/img'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'annee', name: 'annee', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

